package fr.gouv.agora.domain

import fr.gouv.agora.domain.Departement.*

enum class Region(val value: String, private val departements: List<Departement>) {
    AUVERGNE_RHONE_ALPES("Auvergne-Rhône-Alpes", listOf(
        AIN,
        ALLIER,
        ARDECHE,
        CANTAL,
        DROME,
        ISERE,
        LOIRE,
        HAUTE_LOIRE,
        PUY_DE_DOME,
        RHONE,
        SAVOIE,
        HAUTE_SAVOIE,
    )),
    BOURGOGNE_FRANCHE_COMTE("Bourgogne-Franche-Comté", listOf(
        COTE_D_OR,
        DOUBS,
        JURA,
        NIEVRE,
        HAUTE_SAONE,
        SAONE_ET_LOIRE,
        YONNE,
        TERRITOIRE_DE_BELFORT,
    )),
    BRETAGNE("Bretagne", listOf(
        COTES_D_ARMOR,
        FINISTERE,
        ILLE_ET_VILAINE,
        MORBIHAN,
    )),
    CENTRE_VAL_DE_LOIRE("Centre-Val de Loire", listOf(
        CHER,
        EURE_ET_LOIR,
        INDRE,
        INDRE_ET_LOIRE,
        LOIR_ET_CHER,
        LOIRET,
    )),
    CORSE("Corse", listOf(
        CORSE_DU_SUD,
        HAUTE_CORSE,
    )),
    GRAND_EST("Grand Est", listOf(
        ARDENNES,
        AUBE,
        MARNE,
        HAUTE_MARNE,
        MEURTHE_ET_MOSELLE,
        MEUSE,
        MOSELLE,
        BAS_RHIN,
        HAUT_RHIN,
        VOSGES,
    )),
    HAUTS_DE_FRANCE("Hauts-de-France", listOf(
        AISNE,
        NORD,
        OISE,
        PAS_DE_CALAIS,
        SOMME,
    )),
    ILE_DE_FRANCE("Ile-de-France", listOf(
        PARIS,
        SEINE_ET_MARNE,
        YVELINES,
        ESSONNE,
        HAUTS_DE_SEINE,
        SEINE_SAINT_DENIS,
        VAL_DE_MARNE,
        VAL_D_OISE,
    )),
    NORMANDIE("Normandie", listOf(
        CALVADOS,
        EURE,
        MANCHE,
        ORNE,
        SEINE_MARITIME,
    )),
    NOUVELLE_AQUITAINE("Nouvelle-Aquitaine", listOf(
        CHARENTE,
        CHARENTE_MARITIME,
        CORREZE,
        CREUSE,
        DORDOGNE,
        GIRONDE,
        LANDES,
        LOT_ET_GARONNE,
        PYRENEES_ATLANTIQUES,
        DEUX_SEVRES,
        VIENNE,
        HAUTE_VIENNE,
    )),
    OCCITANIE("Occitanie", listOf(
        ARIEGE,
        AUDE,
        AVEYRON,
        GARD,
        HAUTE_GARONNE,
        GERS,
        HERAULT,
        LOT,
        LOZERE,
        HAUTES_PYRENEES,
        PYRENEES_ORIENTALES,
        TARN,
        TARN_ET_GARONNE,
    )),
    PAYS_DE_LA_LOIRE("Pays de la Loire", listOf(
        LOIRE_ATLANTIQUE,
        MAINE_ET_LOIRE,
        MAYENNE,
        SARTHE,
        VENDEE,
    )),
    PROVENCE_ALPES_COTE_D_AZUR("Provence Alpes Côte d’Azur", listOf(
        ALPES_DE_HAUTE_PROVENCE,
        HAUTES_ALPES,
        ALPES_MARITIMES,
        BOUCHES_DU_RHONE,
        VAR,
        VAUCLUSE,
    )),
    GUADELOUPE("Guadeloupe", emptyList()),
    MARTINIQUE("Martinique", emptyList()),
    GUYANE("Guyane", emptyList()),
    LA_REUNION("La Réunion", emptyList()),
    MAYOTTE("Mayotte", emptyList()),
    SAINT_PIERRE_ET_MIQUELON("Saint-Pierre-et-Miquelon", emptyList()),
    SAINT_BARTHELEMY("Saint-Barthélémy", emptyList()),
    SAINT_MARTIN("Saint-Martin", emptyList()),
    TERRES_AUSTRALES_ET_ANTARCTIQUES_FRANCAISES("Terres australes et antarctiques françaises", emptyList()),
    WALLIS_ET_FUTUNA("Wallis-et-Futuna", emptyList()),
    POLYNESIE_FRANCAISE("Polynésie française", emptyList()),
    NOUVELLE_CALEDONIE("Nouvelle-Calédonie", emptyList()),;

    fun getDepartementsNames(): List<String> {
        return this.departements.map { it.value }
    }
}
